# Basic PyTorch Tensor Manipulation Practice

## Guideline:
Submit your completed code for each task, organized into sections with comments. Document your code and provide a brief summary of each task's accomplishment. Good luck with your PyTorch practice!

## Task 1: Tensor Creation and Basic Operations
1. Create two 3x3 matrices (tensors) A and B with random integer values between 1 and 10.
2. Print the matrices A and B.
3. Calculate the element-wise sum of A and B.
4. Calculate the element-wise product of A and B.

In [1]:
import torch

In [27]:
#you code goes here
A=torch.randint(1,11,(3,3))
B=torch.randint(1,11,(3,3))
print(A)
print(B)
print(A+B)
print(A*B)

tensor([[4, 9, 5],
        [1, 1, 1],
        [9, 9, 9]])
tensor([[5, 9, 8],
        [2, 8, 8],
        [7, 5, 4]])
tensor([[ 9, 18, 13],
        [ 3,  9,  9],
        [16, 14, 13]])
tensor([[20, 81, 40],
        [ 2,  8,  8],
        [63, 45, 36]])


## Task 2: Tensor Reshaping and Slicing
1. Create a 1D tensor C of size 9 with values from 0 to 8.
2. Reshape C into a 3x3 matrix D.
3. Print the shape of tensor D.
4. Slice tensor D to obtain the submatrix containing the last two rows and last two columns.


In [15]:
#you code goes here
C=torch.randint(0,9,(9,))
print(f"C: {C}")
D=C.reshape(3,3)
print(f"D: {D}")
print(f"DShape of D: {D.shape}")
print(f"SLicing: {D[1:,1:]}")

C: tensor([2, 8, 0, 6, 4, 6, 4, 2, 8])
D: tensor([[2, 8, 0],
        [6, 4, 6],
        [4, 2, 8]])
DShape of D: torch.Size([3, 3])
SLicing: tensor([[4, 6],
        [2, 8]])


## Task 3: Mathematical Operations and Broadcasting
1. Create a tensor E with values [1, 2, 3].
2. Add a scalar value 5 to tensor E and print the result.
3. Multiply tensor E by a scalar value 2.5 and print the result.

In [17]:
#you code goes here
E=torch.tensor([1,2,3])
print(E+5)
print(E*2.5)

tensor([6, 7, 8])
tensor([2.5000, 5.0000, 7.5000])


## Task 4: Reduction Operations
1. Create a random 4x4 matrix F with values between 0 and 1.
2. Calculate the mean of all elements in tensor F.
3. Calculate the sum of each column in tensor F.
4. Calculate the maximum value along the rows of tensor F.

In [8]:
#you code goes here
F=torch.rand(4,4)
print('F:',F)
print(f"mean: {torch.mean(F)}")
print(f"sum of each column: {torch.sum(F, dim=0)}")
print(f"max of each row: {torch.max(F, dim=1)}")

F: tensor([[0.1080, 0.5383, 0.1873, 0.6276],
        [0.8894, 0.2293, 0.9584, 0.2748],
        [0.0962, 0.6201, 0.5234, 0.0841],
        [0.8783, 0.2363, 0.9733, 0.9213]])
mean: 0.509137749671936
sum of each column: tensor([1.9720, 1.6240, 2.6424, 1.9078])
max of each row: torch.return_types.max(
values=tensor([0.6276, 0.9584, 0.6201, 0.9733]),
indices=tensor([3, 2, 1, 2]))


## Task 5: Printing Tensor Shapes
1. Create three tensors G, H, and I with shapes (2, 3), (3, 4), and (4, 5) respectively.
2. Print the shapes of tensors G, H, and I.

In [9]:
#you code goes here
G=torch.randint(1,101,(2,3))
H=torch.randint(1,101,(3, 4))
I=torch.randint(1,101,(4, 5))
print(f"shape of G: {G.shape}")
print(f"shape of H: {H.shape}")
print(f"shape of I: {I.shape}")

shape of G: torch.Size([2, 3])
shape of H: torch.Size([3, 4])
shape of I: torch.Size([4, 5])


## Task 6: Matrix Multiplication
1. Create two random matrices M1 of shape (3, 4) and M2 of shape (4, 2).
2. Perform matrix multiplication between M1 and M2 and print the result.


In [10]:
#you code goes here
M1=torch.randint(1,11,(3, 4))
M2=torch.randint(1,11,(4,2))
print(f"M1: \n{M1}\nM2:\n{M2}")
print(f"matrix multiplication: {torch.mm(M1,M2)}")

M1: 
tensor([[6, 3, 5, 8],
        [3, 8, 1, 1],
        [1, 9, 9, 9]])
M2:
tensor([[4, 4],
        [7, 7],
        [1, 9],
        [8, 1]])
matrix multiplication: tensor([[114,  98],
        [ 77,  78],
        [148, 157]])


## Task 7: Indexing and Slicing
1. Create a 2D tensor J of shape (5, 5) with consecutive integers from 0 to 24.
2. Print the element at row 3 and column 4.
3. Slice tensor J to obtain a 3x3 submatrix from rows 1 to 3 and columns 1 to 3.

In [15]:
#you code goes here
J=torch.randint(0,25,(5,5))
print(J)
print(J[2][3])
print(J[:3,:3])

tensor([[19, 17,  2, 19, 13],
        [14,  9, 17,  4, 16],
        [ 4,  2, 12,  8,  9],
        [22, 11, 14,  8, 18],
        [17, 10,  9,  9, 22]])
tensor(8)
tensor([[19, 17,  2],
        [14,  9, 17],
        [ 4,  2, 12]])


## Task 8: Transpose and Permutations
1. Create a tensor K with shape (2, 3, 4).
2. Transpose tensor K to have dimensions (4, 2, 3).
3. Perform a permutation of the dimensions to achieve (3, 2, 4).
4. Print the shapes after each transformation.

In [16]:
#you code goes here
K=torch.randint(0,11,(2,3,4))
print(K)


tensor([[[ 4,  9,  5,  1],
         [ 4, 10,  0,  4],
         [ 0,  5,  1,  1]],

        [[ 5,  3,  9,  8],
         [ 3,  9,  5,  7],
         [ 9,  9,  2,  3]]])


## Task 9: Element-wise Function Application
1. Create a tensor L with random values between -1 and 1.
2. Apply the sine function (torch.sin) to every element of tensor L.
3. Calculate the absolute value of the result using torch.abs.

In [26]:
#you code goes here
L=torch.rand(5)
L=2*L-1
print(L)
print(torch.sin(L))
print(torch.abs(torch.sin(L)))


tensor([ 0.7600,  0.6656,  0.4184,  0.0582, -0.2218])
tensor([ 0.6889,  0.6175,  0.4063,  0.0582, -0.2200])
tensor([0.6889, 0.6175, 0.4063, 0.0582, 0.2200])


## Task 10: GPU Acceleration (Optional, if GPU is available)
1. Check if a GPU is available for computation (torch.cuda.is_available()).
2. If a GPU is available, move one of your tensors from Task 1 (A or B) to the GPU and perform a simple operation (e.g., addition) on it using GPU acceleration.

In [30]:
#you code goes here
print(torch.cuda.is_available())
A=A.cuda()
print(A)
print(5+A)

True
tensor([[4, 9, 5],
        [1, 1, 1],
        [9, 9, 9]], device='cuda:0')
tensor([[ 9, 14, 10],
        [ 6,  6,  6],
        [14, 14, 14]], device='cuda:0')


## Task 11: Broadcasting with Different Shapes
1. Create a 2D tensor M of shape (3, 3).
2. Create a 1D tensor N of shape (3,).
3. Add tensor M to tensor N, and observe how broadcasting works with tensors of different shapes.

In [ ]:
#you code goes here

## Task 12: Advanced Reduction Operations
1. Create a 2D tensor O with random values.
2. Calculate the sum of each row and find the index of the row with the maximum sum.
3. Calculate the mean of each column and find the index of the column with the minimum mean.

In [ ]:
#you code goes here