## NumPy Assignment
These assignments involve common tasks encountered in data analysis, finance, and image processing, where NumPy can be applied to efficiently manipulate and analyze data. They require intermediate knowledge of NumPy functions such as sum, mean, nanmean, std, reshape, and dot product, among others.

Remember to consult the NumPy documentation and other resources for detailed explanations of the functions and concepts involved in these assignments.

### Assignment 1: Sales Analysis
You are given an array representing the daily sales of a product for a week. Your task is to find the total sales for the week and calculate the average daily sales.

**Data:** An array representing the daily sales of a product for a week.

```python
sales = np.array([50, 45, 55, 60, 48, 52, 58])
```

In [1]:
import numpy as np

In [7]:
sales = np.array([50, 45, 55, 60, 48, 52, 58])
print(f"Total sales: {np.sum(sales)}")
print(f"Average sales: {np.average(sales)}")

Total sales: 368
Average sales: 52.57142857142857


### Assignment 2: Data Cleaning
You have a dataset containing customer ratings for various products. However, some ratings are missing **`(NaN values)`**. Your task is to replace all the missing ratings with the mean rating for each product.

**Data:** A dataset containing customer ratings for various products with missing values (NaN).

```python
ratings = np.array([3.5, 4.2, 2.8, np.nan, 3.9, np.nan, 4.5, 3.2, 3.7])
```

In [19]:
ratings = np.array([3.5, 4.2, 2.8, np.nan, 3.9, np.nan, 4.5, 3.2, 3.7])
#print(np.nanmean(ratings))
#print(np.isnan(ratings))
ratings=np.where(np.isnan(ratings),np.nanmean(ratings),ratings)
print(ratings)

[3.5        4.2        2.8        3.68571429 3.9        3.68571429
 4.5        3.2        3.7       ]


### Assignment 3: Image Processing
You are working on an image processing project and need to apply a grayscale filter to an RGB image. Convert the RGB image into a grayscale image using numpy arrays and the appropriate color channel weights **`(e.g., 0.2989 * Red + 0.5870 * Green + 0.1140 * Blue)`**.

**Data:** An RGB image represented as a 3D numpy array with shape **`(height, width, 3)`**, where the third dimension represents the Red, Green, and Blue color channels.

```python
image = np.array([[[255, 0, 0], [0, 255, 0], [0, 0, 255]],
                  [[127, 127, 127], [255, 255, 255], [0, 0, 0]],
                  [[100, 200, 50], [150, 75, 200], [25, 125, 75]]], dtype=np.uint8)
```

**`Output will be:`**
```lua
[[  76.197  76.197  76.197]
 [ 166.595 166.595 166.595]
 [ 148.293 148.293 148.293]]
 ```

In [37]:
image = np.array([[[255, 0, 0], [0, 255, 0], [0, 0, 255]],
                  [[127, 127, 127], [255, 255, 255], [0, 0, 0]],
                  [[100, 200, 50], [150, 75, 200], [25, 125, 75]]], dtype=np.uint8)
print(image[:,:,2]*0.1140)
print("")
print(image[:,:,1]*0.5870)
print("")
print(image[:,:,0]*0.2989)


[[ 0.     0.    29.07 ]
 [14.478 29.07   0.   ]
 [ 5.7   22.8    8.55 ]]

[[  0.    149.685   0.   ]
 [ 74.549 149.685   0.   ]
 [117.4    44.025  73.375]]

[[76.2195  0.      0.    ]
 [37.9603 76.2195  0.    ]
 [29.89   44.835   7.4725]]


### Assignment 4: Images Data Manupulation
You are given an image of shape **`(1000,667,3)`**. Perform the following task:
   - convert the images to a numpy array
   - Expand the dimension of image array to **`(1,1000,67,3,1)`**
   - Remove all single dimensions from the numpy array     
##### Load Image
```python
from PIL import Image
image1 = Image.open("images/cat.jpg")
```

In [42]:
image = np.random.randint(0, 256, size=(1000, 667, 3), dtype=np.uint8)
#print(image)
image_array = np.array(image)
print(image_array)

[[[ 30 153 177]
  [153 102 191]
  [129  69 135]
  ...
  [ 39   1  66]
  [ 48 217  84]
  [247  79  72]]

 [[ 34  57 238]
  [163 104 217]
  [ 73 182 170]
  ...
  [111 131  82]
  [193 151 122]
  [ 69  77 207]]

 [[223  93  26]
  [121  86 135]
  [212 153 142]
  ...
  [ 48 216 157]
  [ 12  45 159]
  [161  85 193]]

 ...

 [[ 56 149  20]
  [ 85 240  15]
  [ 61   7 222]
  ...
  [219 127 223]
  [238 247  55]
  [234 110  85]]

 [[ 49 149 238]
  [251  57 232]
  [255 224  47]
  ...
  [249  69   4]
  [117  93 116]
  [162  89 192]]

 [[ 21  49  26]
  [114 199 203]
  [156 136 223]
  ...
  [223  34  23]
  [231 220 231]
  [161  79  73]]]
